# Generated by Django 4.1.12 on 2023-11-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_of_transaction',
            field=models.DateField(help_text='Date of transaction'),
        ),
    ]
